name: test-environment
channels:
  - conda-forge
dependencies:
  - python=3.9
  - dask[dataframe,distributed]
  - pyarrow
  - pytest
  - mypy==0.991
  - mypy-extensions==0.4.3
  - pytest==7.2.0
  - pytest-cov==4.0.0
  - black==22.3.0
  - mock==4.0.3
